#!/bin/bash
# Script to help fix GitHub Pages environment configuration

echo "🔧 GITHUB PAGES ENVIRONMENT FIXER"
echo "=================================="
echo ""
echo "This script helps you configure the GitHub Pages environment."
echo ""

REPO="XavierCapmarti/insightboard"
ENV_URL="https://github.com/${REPO}/settings/environments/new"

echo "📋 MANUAL STEPS REQUIRED:"
echo ""
echo "1. Go to GitHub repository settings:"
echo "   https://github.com/${REPO}/settings/environments"
echo ""
echo "2. If 'github-pages' environment doesn't exist:"
echo "   - Click 'New environment'"
echo "   - Name it: github-pages"
echo "   - Click 'Configure environment'"
echo ""
echo "3. Under 'Deployment branches':"
echo "   - Select 'All branches' OR"
echo "   - Select 'Selected branches' and add 'main'"
echo ""
echo "4. Click 'Save protection rules'"
echo ""
echo "5. Verify the workflow runs again"
echo ""
echo "🔗 Direct links:"
echo "   - Environments: https://github.com/${REPO}/settings/environments"
echo "   - Pages settings: https://github.com/${REPO}/settings/pages"
echo "   - Actions: https://github.com/${REPO}/actions"
echo ""
echo "⚠️  NOTE: You must have admin access to the repository to configure environments."
echo ""
